In [21]:
import numpy as np
def sigmoid(x,deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [22]:
x = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1],
    [0,0,1]
])
print(x.shape)

(5, 3)


In [23]:
y = np.array([
    [0],
    [1],
    [1],
    [1],
    [0]
])
print(y.shape)

(5, 1)


In [24]:
# 随机种子，每次随机初始化一样
np.random.seed(1)

In [25]:
#定义4层神经网络
w0 = 2 * np.random.random((3,4)) - 1
w1 = 2 * np.random.random((4,5)) - 1
w2 = 2 * np.random.random((5,1)) - 1
print(w0)
print(w1)
print(w2)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955   0.75623487 -0.94522481  0.34093502 -0.1653904 ]
 [ 0.11737966 -0.71922612 -0.60379702  0.60148914  0.93652315]
 [-0.37315164  0.38464523  0.7527783   0.78921333 -0.82991158]
 [-0.92189043 -0.66033916  0.75628501 -0.80330633 -0.15778475]]
[[ 0.91577906]
 [ 0.06633057]
 [ 0.38375423]
 [-0.36896874]
 [ 0.37300186]]


In [26]:
for j in range(60000):
    l0 = x
    l1 = sigmoid(np.dot(l0,w0))
    l2 = sigmoid(np.dot(l1,w1))
    l3 = sigmoid(np.dot(l2,w2))
    l3_error = y - l3
    if j%10000 == 0:
        print(f'Error{np.mean(np.abs(l3_error))}')
    l3_delta = l3_error * sigmoid(l3,deriv=True)
    l2_error = l3_delta.dot(w2.T)
    l2_delta = l2_error * sigmoid(l2,deriv=True)
    l1_error = l2_delta.dot(w1.T)
    l1_delta = l1_error * sigmoid(l1,deriv=True)
    
    w2 += l2.T.dot(l3_delta)
    w1 += l1.T.dot(l2_delta)
    w0 += l0.T.dot(l1_delta)

Error0.46752265967564177
Error0.0034746943567726648
Error0.002385161944075119
Error0.001918897316059151
Error0.0016460065958499095
Error0.0014620467837984056


In [28]:
input = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1],
    [0,0,1]
])
l0 = input
l1 = sigmoid(np.dot(l0,w0))
l2 = sigmoid(np.dot(l1,w1))
l3 = sigmoid(np.dot(l2,w2))
output = l3
print(output)

[[0.00171612]
 [0.99852228]
 [0.99854247]
 [0.99973008]
 [0.00171612]]
